### ISSUE TITLE
AddEventListener doesn't always give the right event

### ISSUE THREAD

**Issue by michael-sharethis** [InteractiveAdvertisingBureau/iabtcf-es#116]
**Version**
beta.20

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi

**Describe the bug**
after creating a cmpApi instance i'll set its tcString and toggle uiVisible to true. the 'tcloaded' event will get called and not the 'cmpuishown' event. is this the desired behavior on your end?

once i update cmpApi.tcString and set cmpApi.uiVisible = false, the 'useractioncomplete' event is fired. this is the right behavior. however, after this, if update cmpApi.tcString and set cmpApi.uiVisible = true, the 'useractioncomplete' event is fired again... shouldn't the 'cmpuishown' event be fired there instead?

**Comment by nejcsever** [comment]
I totally agree with you. Same happens to me. I just can't get those events to fire correctly as described in IAB TCF specs. Even if I try all combinations setting those values.
Maybe there could be a more transparent way to handle those event scenarios e.g. setting states via function calls instead of setting two variables (tcModel and uiVisible) or something similar. It's just a bit confusing setting both tcModel and uiVisible in correct orders to get events working correctly and there's currently no correct order for events to work correctly.

So here's my idea of a bit different api flow/design and approach. There would be just two functions which would trigger actual events:
* `cmpApi.setUIVisible(tcModel)` -> this would fire `cmpuishown` event
* `cmpApi.finalize(tcModel)` -> this would fire `tcloaded` if UI is not visible and `useractioncomplete` if UI is currently showing

So essentially, usage scenarios would look something like this:
**Example 1: User with no existing consent - Create, Show, Finalize (and optionally re-fire)**
```
const cmpApi = new CmpApi(1, 3, MyCustomCommands);
// Create a TCModel
const tcModel = new TCModel()
cmpApi.setUIVisible(tcModel) // This would trigger 'cmpuishown' event
// Application now displays UI and updates tcModel. Then when user closes the dialog:
cmpApi.finalize(tcModel) // In this scenario, this would trigger 'useractioncomplete'

// If user decides to re-fire dialog, this code would follow:
cmpApi.setUIVisible(tcModel) // This would again trigger 'cmpuishown' event
// UI is displayed again. When user closes the dialog:
cmpApi.finalize(tcModel) // 'useractioncomplete' is triggered again
```

**Example 2: TCData is current and does not need renewal - Create, Finalize (and optionally re-fire)**
```
const cmpApi = new CmpApi(1, 3, MyCustomCommands);
// Create a TCModel from existing/current data (from cookies, local storage or somewhere else)
const tcModel = new TCModel()
// There's no need to call setUIVisible, we just need to finalize since data is current
cmpApi.finalize(tcModel) // In this scenario, this would trigger 'tcloaded' event because UI was not shown

// If user decides to re-fire dialog, this code would follow:
cmpApi.setUIVisible(tcModel) // This would again trigger 'cmpuishown' event
// UI is displayed again. When user closes the dialog:
cmpApi.finalize(tcModel) // 'useractioncomplete' is triggered again
```
**Example 3: GDPR doesn't apply**
```
const cmpApi = new CmpApi(1, 3, MyCustomCommands);
cmpApi.finalize() // Finalize without parameter or it could also be cmpApi.finalize(null)
```

The main difference here between this and current implementation is that "uiVisible" and "tcModel" are combined together into atomic calls and I think more transparent and predictable.

Sorry for the long comment, I just wanted to share my 5 cents if you think this would be a good idea. :)

**Comment by chrispaterson** [comment]
Let me look into this, perhaps I have changed it to the wrong thing...

**Comment by chrispaterson** [comment]
![image](https://user-images.githubusercontent.com/1268493/77015514-3e233f00-6932-11ea-8fa6-cd5fed8a18ca.png)

**Comment by michael-sharethis** [comment]
in this case i am setting a tcString and setting cmpApi.uiVisible to true in order to trigger the event.

**Comment by nejcsever** [comment]
How can we prevent `tcloaded` from happening when the brand new TCModel is created (no current data)? In this case there should only be `cmpuishown` and `useractioncomplete` events.

**Comment by michael-sharethis** [comment]
i agree with @nejcsever on this last point

**Comment by chrispaterson** [comment]
> How can we prevent `tcloaded` from happening when the brand new TCModel is created (no current data)? In this case there should only be `cmpuishown` and `useractioncomplete` events.

Ah, I just re-read the spec for [`eventStatus`](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#addeventlistener) and you are right.  The `tcloaded` event should not fire if it's a new `TCModel`.

> A CMP is only prepared to surface a TC String for this `eventStatus` if an existing, valid TC String is available to the CMP and it is not intending to surface the UI. If, however, the CMP will surface the UI because of an invalid TC String (e.g. it is too old, incorrect or does not reflect all the information the CMP needs to gather from the user) then an event with this `eventStatus` must not be triggered. 

In that case I would think that `cmpApi.uiVisible = false` should be set and then the `tcloaded` will fire.
This would be the updated table:
![image](https://user-images.githubusercontent.com/1268493/77019733-b3950c80-693e-11ea-9dcd-8eda6b4c2e2c.png)

I'll make the changes.

**Comment by nejcsever** [comment]
Thank you Chris, this looks right. 👍
Is it possible in anyway to somehow join/encapsulate those setters together in a function though? It's just a bit confusing setting combinations of uiVisible and tcModel properties, because order in which those are set seems to be very important for correct event flow. And if it is possible in any easy way it would be better for the api to encapsulate setting those values just to make it a bit less error prone. Just a suggestion 🙂

**Comment by chrispaterson** [comment]
I was just considering this... I might just remove the `set uiVisible`, `set tcModel`, and `set tcString` and make it one common function of:

```javascript
update(tcModelOrString, uiVisible);
```

**Comment by michael-sharethis** [comment]
@chrispaterson i think it would be a good idea

**Comment by chrispaterson** [comment]
I'm also considering now making the only option to pass just the string instead of having the option to pass the `TCModel` to simplify the interface and logic in the code.  This would also make it so that the CMP API would not have to download the GVL to encode a string if a `TCModel` was passed.

**Comment by nejcsever** [comment]
Or maybe you can make GVL mandatory to create TCModel. This would then fall onto creation of TCModel instead of decoding it in CmpApi because TCModel would always contain GVL in any case. Is there any case where and why you wouldn't load GVL at all?

**Comment by chrispaterson** [comment]
>  Is there any case where and why you wouldn't load GVL at all?

Sorry I missed this.  Yes there is a case that you wouldn't download the GVL at all and that would be within some "minimum reshow" period.  For example:

1. new user lands on page with CMP
2. CMP sees no TC string
3. CMP downloads GVL and shows UI
4. CMP encodes TC string and saves it
5. user goes to the next page on the site
6. CMP sees a TC string, reads lastUpdated (Date)
7. CMP sees that the TC string was lastUpdated within it's "minimum reshow" period and decides to not do any other checks.
8. The CMP does **NOT** download the GVL.

If there were no "minimum reshow" period the CMP would download the GVL on every page load.  I know there is caching etc, but I bet you publishers who employ the CMP or even those within a mobile In App context would not be happy about the GVL being downloaded on every page.
