### ISSUE TITLE
Vendor consents and vendor legitimate interests in encoded TCString depending on maxId property value from corresponding vectors in TCModel instance.

### ISSUE THREAD

**Issue by mvciekzvbek** [InteractiveAdvertisingBureau/iabtcf-es#131]
**Version**
1.0.0-beta.25

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
When user establishes transparency without any vendor consents nor vendor legitimate interests in decoded consent string values of 'consents' and 'legitimateInterests' keys are empty objects. However, according to docs:  https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata 
'consents' and 'legitimateInterests' objects should both have as many keys as vendors on vendor list with boolean values (in this case all false).

It seems that this is caused by retrieving consents depending on maxId properties from 'vendorConsents' and 'vendorLegitimateInterests' vectors which both are 0.

**Comment by chrispaterson** [comment]
In order to keep TC strings small, each vector is encoded up to the maximum positive value, not the maximum vendor (purpose) ID within that vector on the vendor list.  When the string is decoded (without downloading the vendor list) the maximum value represented in the string is the highest number with a positive consent.  If it's an all "no" TC string that will be "no" keys.  But the technical working groups have decided that is ok because `undefined` and `false` mean the same thing, "no positive consent".
