### ISSUE TITLE
Google's Additional Consent Mode

### ISSUE THREAD

**Issue by dav-m85** [InteractiveAdvertisingBureau/iabtcf-es#176]
Hi, would be great for **@iabtcf/cmpapi** to implement [Google’s Additional Consent Mode technical specification](https://support.google.com/admanager/answer/9681920). Basically it adds a new `addtlConsent ` to `TCData` that reflects the allowed vendors as a dot separated id list (ex: `1~1.35.41.101`).

Any plans on this ? Would you accept a Pull Request ?

I imagine a lot of CMPs are moving forward on this, let's be DRY :)

**Comment by chrispaterson** [comment]
I proposed to the TCF Commit Group that we enable CMPs to wrap the built-in responses with the custom commands and SourcePoint offered to write the feature.  I'm expecting a pull request within the next week.  I think this will enable CMPs to create the `addtlConsent` property on the returned `TCData` object.  Since this is a transitional thing that Google is doing while they migrate their vendors over to the TCF I think that's probably enough.

**Comment by dav-m85** [comment]
Hi @chrispaterson, since you're closing this I imagine the wrapping is now available. Any clues on how to use it ? Is this ok:
```
const cmpApi = new CmpApi(1, 3, true, {getTCData: myHandler})
```
?

**Comment by chrispaterson** [comment]
Sorry, not quite available yet.  I was going to create the feature more broadly as wrapping built-in commands.  I'll link the issue to this one.

But yes, your example is how I was thinking it would work; much like express middleware where you'll return a promise or call `next()` once your wrapper has finished modifying the result.

**Comment by chrispaterson** [comment]
#180
