### ISSUE TITLE
Consent not saving in the consent string for certain vendors

### ISSUE THREAD

**Issue by mguerra10128** [InteractiveAdvertisingBureau/iabtcf-es#207]
**Version**:  "1.1.0"

**Module (core, cmpapi, cli, stub, or testing)**: "@iabtcf/core"

**Describe with reproduction steps – What is the expected behavior?**:
I upgraded the  "@iabtcf/core" from "1.0.1" to "1.1.0"; after which when consenting to certain iab vendors, they dont get saved in the consent string. After downgrading things work again, which leads me to believe its a bug in the latest library. An example vendor is: Adnami Aps; but it happens for others as well.

**Comment by mguerra10128** [comment]
other vendors that dont work:
Adnami Aps
YouGov
AdMaxim
Effinity
Kiosked
A Million Ads
Blue Billywig BV
Cavai AS & UK

**Comment by chrispaterson** [comment]
If they do not declare purposes (either legitimate interest or consent) on the GVL then they can't get a positive signal for it.  This was added to 1.1.0 in issue #165

**Comment by mguerra10128** [comment]
Vendors noted above do have purposes and/or legitimate interest purposes

**Comment by mguerra10128** [comment]
e.g 
`688: {
id: 688,
name: "Effinity",
purposes: [ ],
legIntPurposes: [
2
],
flexiblePurposes: [
2,
7
],
specialPurposes: [ ],
features: [ ],
specialFeatures: [ ],
policyUrl: "https://www.effiliation.com/politique-de-confidentialite/",
overflow: {
httpGetLimit: 128
}
},`

**Comment by chrispaterson** [comment]
688 has nothing in "purposes" ie. no Consent Purposes

**Comment by mguerra10128** [comment]
Chris - Infinity has the flexible purpose 2, and 7. So they do collect consent for those purposes.

**Comment by chrispaterson** [comment]
Going to paste the back-channel email here:

> 688: { id: 688, name: "Effinity", purposes: [ ], legIntPurposes: [ 2 ], flexiblePurposes: [ 2, 7 ], specialPurposes: [ ], features: [ ], specialFeatures: [ ], policyUrl: "https://www.effiliation.com/politique-de-confidentialite/", overflow: { httpGetLimit: 128 } },
>  
> they define the flexiblePurposes 2, 7, which means they are capable of collecting "consent" for it. 
>  
Hmmm…. This is an interesting point I hadn’t considered.  You’re right the encoder should probably look at the flexible purposes and the purpose restrictions before it removes the value.
>  
> Also re the below, was a constraint added so that these vendors wont be included in the encoded string? This has rippling effects so ideally, they would be allowed to be encoded and decoded.
>  
> ·         i observed that that three vendors on the gvl have the following 'deletedDate' field; is this a way of signaling that a vendor was removed from the list?
>  
> Yes that’s right.  CMPs should not capture positive signal values for those vendors.
>  
This has been around since v1, so it’s hard to remember all the reasons why it was created.  I don’t have anything specific to prevent the vendor from being encoded into the string with a positive signal but in the GVL class, they don’t show up on the list if they are “deleted" so that a CMP won’t use display them.  Probably a good idea though to add that to the list of removals on the encoder.

**Comment by chrispaterson** [comment]
I believe this is the same as issue #204

**Comment by chrispaterson** [comment]
These vendors are not because of flexible purposes:

- Adnami Aps
  - Has no flexible purposes – should not be included
- YouGov
  - I do not see this vendor
- AdMaxim
  - Is not included because it has been deleted, ie. has a deletedDate

These are
- Effinity
- Kiosked
- A Million Ads
- Blue Billywig BV
- Cavai AS & UK
