### ISSUE TITLE
cmpStub - gdprApplies param is not working

### ISSUE THREAD

**Issue by LukaszSawicki** [InteractiveAdvertisingBureau/iabtcf-es#232]
**Version**
1.1.4

**Module (core, cmpapi, cli, stub, or testing)**
stub

**Describe with reproduction steps – What is the expected behavior?**
Hi. The **gdprApplies** variable is defined inside **tcfAPIHandler** function so every time any function is invoking variable is redefining and it's value is always undefined.

**Comment by shortaflip** [comment]
v1.2.1-3 of the library has been pre-released, which contains the changes submitted with this issues accompanying PR.  Please try out the pre-release in your environments so that we can confirm the stability in time for the actual release next week on Tues.  Let me know if any bugs from this ticket are found so that I can push these changes to a different release and verify that v1.2.1 without these changes are stable.  Thank you.

**Comment by shortaflip** [comment]
v1.2.1 of the library that contains the changes from the PR that closed this ticket is live.
