### ISSUE TITLE
Vendor ranges not properly encoded for publisher restrictions

### ISSUE THREAD

**Issue by kemalmustafic** [InteractiveAdvertisingBureau/iabtcf-es#261]
**Version**
1.2.1-1

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
When encoding a publisher restriction segment in the consent string and checking whether a vendor range is present, the core library [is checking](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/encoder/field/PurposeRestrictionVectorEncoder.ts#L48) for consecutive vendor IDs (e.g. 1, 2, 3) but instead, it should be checking the consecutive vendor IDs from the vendor list (e.g. 2, 6, 8, 12).

Vendors that don't exist within a range should be ignored when evaluating whether that is a valid range or not.

**Comment by shortaflip** [comment]
@kemalmustafic Hi, were you seeing this bug in the stable version 1.1.4 as well?  

The code changes introduced by 1.2.1-1 [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/projects/14), did not touch any of the code in the `PurposeRestrictionVectorEncoder.ts` file.

Let me know if you are working on this bug, so I can add this to 1.2.1 and push it into another pre-release once it is reviewed and merged in.

**Comment by kemalmustafic** [comment]
@shortaflip Yes, I opened a PR for it

**Comment by chrispaterson** [comment]
I agree @a2intl, that has always been an issue with range encoding; a vendor ID could be added to a later GVL and without the user ever seeing that vendor there could be values set (or not set) for them — because there is no meaningful distinction between a “no” and a “never seen.”  So I was VERY precise about what a “Range” means when I wrote that part of the spec.  There was a concern that if a CMP had an “accept all” button and set the range from 1->maxVendorId that a vendor would have consent (or LI) even if the user never had never even seen the Vendor in a CMP (bad!). That being said, this particular range encoding is within the purpose restrictions and therefore if that Vendor doesn’t exist it won’t have had any legitimate interest or consent values set positively within the respective vendor vectors; and so it becomes somewhat moot. It’s probably ok, but I would run it by Matthias/ Commit Group

**Comment by dmdabbs** [comment]
@a2intl  and @chrispaterson  (hi, Chris), I'm going to bring this to tomorrow's Framework Signals quality WG meeting agenda tomorrow morning. Don;t expect a decision there, but I'll bring it to Anne's attention to get Filip's and others' eyes on it.

**Comment by dmdabbs** [comment]
The Framework Signals group, including Filip and Anne, approved this PR and the relaxed encoding. We must open a PR against the v2 specification to amend the Restrictions section description of the encoding logic. We can release the library upon approval of the Spec update.

cc: @a2intl, @chrispaterson

**Comment by shortaflip** [comment]
v1.2.1-2 of the library has been pre-released.  If all goes well by this day next week, v1.2.1 of the library which contains the changes for this issue will be released.

**Comment by shortaflip** [comment]
v1.2.1-3 of the library has been pre-released.  There were some request yesterday to add two more PRs (230 & 246).  While the PRs should not have any problems, if within a week time any bug from either one is found, I will revert those merges and assign them to the next release.  This way we can get the changes that were originally in queue for 1.2.1 released and have no more delays.

**Comment by shortaflip** [comment]
v1.2.1 of the library that contains the changes from the PR that closed this ticket is live.
