### ISSUE TITLE
TcString new created date when decoded

### ISSUE THREAD

**Issue by majklfly** [InteractiveAdvertisingBureau/iabtcf-es#342]
**Version**
1.4

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**

When I happen to encode the TcModel into a TcString, save to a cookie and another time rebuild it again...it creates a new TcModel with new created date naturally. But that's now what I would like it to do. I would like to get back the tcModel I encoded before including date it has been included.

Apparently it works on your website but not in the library. Is there any chance it can be done or is there something I'm doing wrong?

Thank you for your time and help

Michal

**Comment by dmdabbs** [comment]
When you say "our website" what site are you referring to?

**Comment by majklfly** [comment]
https://iabtcf.com/#/decode

**Comment by majklfly** [comment]
(if not necessary fix I would appreciate tips for workarounds as well...)

**Comment by dmdabbs** [comment]
I see. AFAIK, the decoder hasn't been refreshed with this rev of the community library. So if there's an issue in this version that's why you don't see it there. 
I know some maintainers, perhaps they can investigate when free. 
cc: @anderagakura , @shortaflip

**Comment by shortaflip** [comment]
@majklfly,

Hi, I am busy with internal work and may not get to investigate this for a couple of weeks.

**Comment by shortaflip** [comment]
This is more than likely from the timestamp granularity spec changes that were included in the last release 1.4.0.  The `created` field of the `TCModel` might be initialized in the wrong area.  Will investigate and update with a PR.

**Comment by shortaflip** [comment]
Hi @majklfly,

A bugfix was merged for this issue recently and I have reverted the bugfix.  I was made aware that the issue you filed with the `created` and `lastUpdated` having the same value was due to an update in the technical specs located [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-happened-to-created-and-lastupdated).

This is a new feature of the `iabtcf-es` library.  Issue will remain closed.
