### ISSUE TITLE
Improve library performance when creating publisher restrictions for vendors ids above 4000

### ISSUE THREAD

**Issue by sevriugin** [InteractiveAdvertisingBureau/iabtcf-es#406]
It looks like the core library is slow when working with GVL where vendors ids are above 4000. For the lates GVL update ([v208](https://vendor-list.consensu.org/v2/vendor-list.json)) where we have vendor "Advertising.Tech FZ-LLC" added with id 4176 we have experienced significant delays for TCString encoding / decoding. 

For example this short string:

`CPv0u4APv0u4AAHABBENDQCsAP_AAAAAAAAAJNFT_T_cT3NjeX5_7vt0eY1ew1y-r-giDgKZA6wJSXqAsJwH0mAqKF3AgqgKgB4EIHbBAQBlHAHAREEgQIEBATGMAEWQJRIIIqLAEAIRAgIACAlZHYEQGAIQgPQACDQIkAOGCHsoUOFFOQAgDEAAIAqlAITFAgQYRBCAwIgIDAAIQi4BCAQAayAETEAAAFEIEABZAAEAAABISADAAEQUA0AGAAIgoCIAMAARBQFQAYAAiCgMgAwABEFAdABgACIKBCADAAEQUCUAGAAIgoFIAMAARBQA.f_gAAAAAAAAA` 

takes some time to decode in https://iabtcf.com/?#/decode

It looks like the issue is [here](https://github.com/didomi/iabtcf-es/blob/6ef07a0e6ddc48fe268d629c2c4a1ad457560aca/modules/core/src/encoder/field/PurposeRestrictionVectorEncoder.ts#L18) when we are calling `nextGvlVendor` for each publisher restrictions and for each vendor, as result `encode` takes around 370ms

**Comment by marco-prontera** [comment]
@sevriugin I see that the vendor id that causes this bug doesn't have purposes or legitimate purposes so does it make sense a restriction for vendors like this?

**Comment by marco-prontera** [comment]
@sevriugin Tomorrow I will open the PR to improve performance but the changes must be used by the whole industry (at least by those who use this library).
I tried with the things you said, in fact the encode and decode time is close to 700ms. This is unacceptable, as this long time of encode and decode will degrade performance for everyone.
**After the changes are made, I think the IAB should send an email to all TCF attendees inviting them to upgrade to the new version with this improvement.**

Note about the improvement: I can improve the performance but the behavior will be the same. So the fact that there are vendors that doesn't make sense to have them in the purpose restriction collection **can't be changed** without introducing breaking changes to the TCString. **Because this is what makes the TCString little**, it uses a range of vendor ids, they included all vendors to create as less as possible sub sections into the TCString. You can create manually sub sections for purpose restriction but this will increase considerably the length of the TCString.

I'm sorry but I take this opportunity to invite you (@HeinzBaumann @lamrowena @iabmayank @aitnitishshelage) to collaborate with us because in addition to this issue, there are others with ready PRs that fix very important issues and update the library to TCF v2.2 (where the CMP update deadline is 30 September, we can't update the CMPs in 3 seconds without having time to test everything correctly).
