### ISSUE TITLE
TC string larger than 4096 bytes

### ISSUE THREAD

**Issue by jelenatomcic** [InteractiveAdvertisingBureau/iabtcf-es#419]
**Version**
1.5.9
**Module (core, cmpapi, cli, stub, or testing)**
core
**Describe with reproduction steps – What is the expected behavior?**
TC string created using GVLv3 and version 1.5.9 of core lib is in our case 4642 bytes big. With the previous version it was much smaller. We are setting publisher restrictions REQUIRE_CONSENT for all purposes and vendors. In the previous version method restrictPurposeToLegalBasis of TCModel was setting the restrictions in another way. I attached the big TC string. 
We need a solution for this, since we need to store the TC string in the cookie.

[tcstring-GVLv3-core-1.5.9.txt](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/files/12598363/tcstring-GVLv3-core-1.5.9.txt)

**Comment by sevriugin** [comment]
@marco-prontera could this one related to then performance fix for the publisher restriction ?

**Comment by asr-enid** [comment]
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/e1ac2ff132254036fc5a97ae9b678634791f0c08

This commit changed the implementation of restrictPurposeToLegalBasis to using a set instead of bst for the list of all vendors. I assume that leads to the problem in such that the vendorIDs are not inserted in increasing order (guess it will be random in a sense) as the code iterates through the set. That will lead to the encoder not generating 1 Range from 1...MAX_Vendor, but hundrets and hunderds of segments.

**Comment by asr-enid** [comment]
old code to get sorted vendorIDs

`/**
     * Create an ordered array of vendor IDs from `1` (the minimum value for Vendor ID) to `lastEntry`
     */
    const values = [...Array(lastEntry).keys()].map( (i) => i + 1);`

**Comment by marco-prontera** [comment]
Hi @sevriugin it could be related.
@asr-enid the sort is also done in that commit [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/e1ac2ff132254036fc5a97ae9b678634791f0c08?diff=unified#diff-8ff63e5f4d33a99f596ea57d2d72dea7782ae36d9eff80c7e518145a2eef2d78R207), I'm trying to reproduce the problem since I also use the method restrictPurposeToLegalBasis and the generated TCString is 357 bytes.
Of course any help is appreciated, since I'm very busy right now

**Comment by marco-prontera** [comment]
> [e1ac2ff](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/e1ac2ff132254036fc5a97ae9b678634791f0c08)
> 
> This commit changed the implementation of restrictPurposeToLegalBasis to using a set instead of bst for the list of all vendors. I assume that leads to the problem in such that the vendorIDs are not inserted in increasing order (guess it will be random in a sense) as the code iterates through the set. That will lead to the encoder not generating 1 Range from 1...MAX_Vendor, but hundreds and hundreds of segments.
> 
> Thus the string blows up in size 10x - the optimisation of restrictPurposeToLegalBasis only works with creating a pre-sorted set of vendor IDs.

@asr-enid here https://codesandbox.io/s/cocky-voice-h6ktnj you can see a little test one with the vendor list as iab give us, and another with vendor ids in a different order (it's the same only with some vendor in different order).
The TCString in output is the same (see in console).

I think @jelenatomcic need to explain how to replicate exactly the problem described in the issue so it will be more easy to fix.

**Comment by marco-prontera** [comment]
> @marco-prontera could this one related to then performance fix for the publisher restriction ?

@sevriugin As you can see from the tests for that thing, it checks the order and segment created by the restrictions. There is also a test for out-of-order vendor IDs. If something from the changes broke the encoding of the TCString the tests would most likely fail. As the tests pass, I believe this problem could either be related, or a problem that was already present.

**Comment by jelenatomcic** [comment]
@marco-prontera I have tested it myself outside of our application and can confirm that TC string is of normal size when we are not using gvl.narrowVendorsTo(). We are and need to use narrowVendorsTo, because we need disclosed vendors segment. If it helps, I'll send you the code, just let me know.

**Comment by jelenatomcic** [comment]
@marco-prontera Here the codesandbox 
https://codesandbox.io/p/sandbox/node-js-forked-pxjhvz?file=/package.json:1,1

**Comment by marco-prontera** [comment]
> @marco-prontera Here the codesandbox https://codesandbox.io/p/sandbox/node-js-forked-pxjhvz?file=/package.json:1,1

Thank you for your help.
I just opened the PR to fix this, I also implemented a test for the thing you said.

**Comment by jelenatomcic** [comment]
Thank you for your quick response.

**Comment by avuim** [comment]
When do you expect the release of the fixed version?

**Comment by asr-enid** [comment]
Fixed in 1.5.10 as far as I understood.
