### ISSUE TITLE
CMP Validator 2.2 comparing vendorlist versions from gvl 2 and 3

### ISSUE THREAD

**Issue by n-lee-commits** [InteractiveAdvertisingBureau/iabtcf-es#420]
Not sure if this is the right channel to go through for the validator logic. If this isn't the right channel, let me know if there's some contact I can get for resolving the issue that I'm seeing here. But it looks like I'm failing technical compliance check 7 for latest gvl version due to the validator pulling in version 2 of the gvl vs version 3.

If there's anything that I'm missing implementation wise that might be triggering this behavior let me know. Otherwise I feel like it might be a bug.

![Screen Shot 2023-09-13 at 12 25 38 PM](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/assets/61883245/87c85a1d-f0cb-46e5-bd77-45e1489507c6)

**Comment by BenBornschein** [comment]
The validator is not able to check for 2.2, it always compares with the v2 vendor list instead of the v3 vendor list.

For 2.2, the validator must use this provider list: https://vendor-list.consensu.org/v3/vendor-list.json

<img width="674" alt="CleanShot 2023-09-25 at 10 58 31@2x" src="https://github.com/InteractiveAdvertisingBureau/iabtcf-es/assets/60609600/87980e0a-e172-42e5-a6c7-ea4d64ea5ff8">

**Comment by BenBornschein** [comment]
An update to the Chrome extension is on the way, as confirmed to us today via email.

**Comment by HeinzBaumann** [comment]
Update CMP validator 2.2 is available on the Chrome Store. @BenBornschein, @n-lee-commits, please let me know if this is still an issue so I can either follow up on it of close this issue. Thanks!

**Comment by BenBornschein** [comment]
@HeinzBaumann version 2.2.3 works fine.
