### ISSUE TITLE
Consented purposes/ Special features in the tcData object returning as empty object rather having false value when consent is not given

### ISSUE THREAD

**Issue by mghouseonetrust** [InteractiveAdvertisingBureau/iabtcf-es#57]
According to the documentation: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#getinapptcdata
When consent is not given, tcData object should return false value but it returns empty object or sometimes consent for only few purposes based on the selection. So the response of the Api's is not consistent across all the conditions.
Please find below screen shot:
![image](https://user-images.githubusercontent.com/45361539/73177424-ff90b580-4134-11ea-9a48-134ba585b97e.png)
 
In this vendorConsent object is empty object and disclosedVendor is a object. Below is the response for mobile API, which is empty string but the consent should be based on bit position.
![image](https://user-images.githubusercontent.com/45361539/73177750-c4db4d00-4135-11ea-8b7a-20f727b3f3a3.png)

**Comment by chrispaterson** [comment]
This is expected – If a value is not present (`undefined`) it is `false`.  Otherwise a GVL is required to decode a TC string because a "max id" is not known based on the encoding.  We are trying to avoid requiring a GVL to decode a TC string.  So in the case of the InApp TCData, if `consent[n] === undefined` the value is `false`
