### ISSUE TITLE
Can I avoid retrieving older versions of vendor list?

### ISSUE THREAD

**Issue by DianeJane** [InteractiveAdvertisingBureau/iabtcf-es#69]
Hi all,

From [Global vendor list](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-global-vendor-list) 
> Where ‘vendor-list-version’ corresponds to the ‘vendorListVersion’ property in the GVL, for example, the following URL would retrieve the GVL update published with version 138
> 
> https://vendorlist.consensu.org/v2/archives/vendor-list-v138.json
> 
> Previous versions of the GVL may only be used in cases when the current version cannot be downloaded (such as when operating in-app while offline), or for change control management.

With CmpApi tool, this call happens automatically but can I configure the API to not retrieve the older version of the list? Or is this something that's required?

**Comment by chrispaterson** [comment]
The only place the API tool gets the vendor list is if the 'getVendorList' command is called.  That command, if implemented, is required to get the version that is specified.

**Comment by chrispaterson** [comment]
I'm wondering if I should make a way to specify which "optional" commands to support.  Does that support your use case?

**Comment by DianeJane** [comment]
Hi @chrispaterson, I haven't been using the `getVendorList` command as of the moment; the (older version of) vendor list is retrieved when I assign the `TCModel` (retrieved from decoded TCString) to `CmpApi.tcModel` (see below):
```
const decodedTCModel = TCString.decode(data.cookie);
cmpApi.tcModel = decodedTCModel;
```

**Comment by DianeJane** [comment]
Related but not the same issue (let me know if I need to open a new issue): is there also a way I can disable retrieving of translated purpose descriptions? The vendor-list we've implemented auto translates the content so calling the language file is redundant.

**Comment by chrispaterson** [comment]
I'll investigate this.  I think I might have introduced this because I made it so that you can set tcModel.vendorListVersion (if a GVL is not set) and it will retrieve the vendor list at that version if the TCModel was not created from a TCString parse.  However, I think because the cmpapi clones the TCModel, it might be triggering the GVL download when the vendor list version is set on the clone.

**Comment by chrispaterson** [comment]
I think we might be able to avoid this if instead of passing the TCModel you could just pass the TC String.  In fact, that would make the library more independent.  The problem is that we are passing the TCModel api and since the TCData object has the string in it, it has to encode the TCModel into a string to be able to surface that.  This is related to #70 and if we changed the interface it would solve both problems.

**Comment by DianeJane** [comment]
Ah I see, that makes sense. Being able to pass `TCString` is a good idea. Thank you!
