### ISSUE TITLE
ReferenceError while calling TCString.decode without global atob

### ISSUE THREAD

**Issue by Jofator** [InteractiveAdvertisingBureau/iabtcf-es#92]
**Version**
"@iabtcf/core": "^1.0.0-beta.13"

**Module**
core

**Describe the bug**
Running sample decodedTCModel = TCString.decode(encodedString);
Ends up with  ReferenceError: atob is not defined
    at Function.e.decode (/home/jape/samples/js/node_modules/@iabtcf/core/lib/encoder/Base64Url.js:1:908)
    at Function.e.decode (/home/jape/samples/js/node_modules/@iabtcf/core/lib/encoder/SegmentEncoder.js:1:932)
    at Function.e.decode (/home/jape/samples/js/node_modules/@iabtcf/core/lib/TCString.js:1:1284)
    at Object.<anonymous> (/home/jape/samples/js/src/iabtcf.js:26:31)
 
**Steps to Reproduce**
Try to call TCString.decode(encodedString) with any valid encodedString

**Expected behavior**
Package "@iabtcf/core" must not rely on global function atob.

**Actual behavior**
Package "@iabtcf/core" DOES rely on global function atob.

**Comment by chrispaterson** [comment]
I'm guessing this is in a node environment?  I'm not sure how to solve this because I don't want to add code for atob/btoa to the bundle for browsers which have that functionality built in.

**Comment by vincent-ogury** [comment]
using Buffer directly is browser and server compatible. making it natively incompatible with nodejs is not a good solution. 

I have do a quick fix by defined into global those 2 methods. but it is ugly. 

I have also see that baseURL for GVL doesn’t work because it rely on XMLHTTPRequest. may be “fetch” should be used instead. 

it is like this package on the opposite of consentString is focused on browser only and ensure let down server backend. 

did few additional codes (1 line per function) packed and probably gzip on cdn will hurt so much?

may be create one release for nodejs and another for browser (a min version hosted on a cdn).

**Comment by chrispaterson** [comment]
Good tips, I'll look into this.  In the @iabtcf/cli package I created the atob/btoa methods with Buffer.  I'll just use that instead for the [Base64Url](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/encoder/Base64Url.ts) class.  Or if you want to take a stab at it, I'll review the pull request.

I'm not really that familiar with "fetch". but the [Json](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/Json.ts) class has the `XMLHttpRequest` stuff in it.

**Comment by Jofator** [comment]
Implement methods itself using Buffer would be great :+1:  see below.
`const atob = b => Buffer.from(b, 'base64').toString('binary');
const btoa = a => Buffer.from(a, 'binary').toString('base64');
`

**Comment by chrispaterson** [comment]
After investigating, I don't think the fetch api is a good choice here because it blocks cookies from being set which may be useful to some.  I think using something like this for node would be a good idea instead: https://github.com/pwnall/node-xhr2
